name: Run textlint
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install packages
      run: npm ci
    - name: Run textlint (Red)
      # continue-on-error: true
      run: npx textlint sample/red.md
    - name: Run textlint (Green)
      run: npx textlint sample/green.md