name: Build and Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install textlint
      run: npm ci
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run textlint (Green)
      run: npx textlint sample/green.md
    - name: Run textlint (Red)
      continue-on-error: true
      run: npx textlint sample/red.md